#PROBLEM 2 - PROJECT EULER
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#find the sum of the even-valued terms.

def even_fibonacci_sum(n)
    primary_cell = [1, 2]
    primary_sum = 0
    (n - 2).times do 
        primary_cell << primary_cell[-1] + primary_cell[-2]
    end
    primary_cell.each { |num| primary_sum += num if num % 2 == 0 }
    p primary_sum
end

even_fibonacci_sum(40)